# Generated by Django 5.1 on 2024-11-23 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulExternalInstallDay',
            fields=[
                ('externalinstallday_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='external_stats.externalinstallday')),
            ],
            bases=('external_stats.externalinstallday',),
        ),
    ]
