# Generated by Django 5.1 on 2024-12-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_stats', '0002_successfulexternalinstallday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessfulExternalInstallDay',
        ),
    ]
