# Generated by Django 5.1 on 2024-12-17 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_stats', '0003_delete_successfulexternalinstallday'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulExternalInstallDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications', models.JSONField()),
                ('installations', models.IntegerField(default=0)),
                ('wallpaper_count', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
